builders:
  git_info_builder:
    import: "package:fstation/builder/git_info_builder.dart"
    builder_factories: ["gitInfoBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
    build_to: source

targets:
  $default:
    builders:
      fstation|git_info_builder:
        generate_for:
          - lib/**