name: fstation
description: "A project help people enjoy their own service and data"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  logging: ^1.3.0
  sentry_flutter: ^8.9.0
  dio: ^5.7.0
  sizer: ^3.0.4
  path_provider: ^2.1.5
  collection: ^1.18.0
  settings_ui: ^2.0.2
  flutter_animate: ^4.5.0
  checkmark: ^0.0.2+1
  intl_utils: ^2.8.7
  smooth_page_indicator: ^1.2.0+3
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.8.0
  responsive_framework: ^1.5.1
  url_launcher: ^6.3.1
  cached_network_image: ^3.3.1
  google_nav_bar: ^5.0.7
  icons_plus: ^5.0.0
  image: ^4.3.0
  flutter_displaymode: ^0.6.0
  dynamic_color: ^1.7.0
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  device_info_plus: ^11.1.1
  catcher_2: ^2.0.1
  worker_manager: ^7.2.2
  countly_flutter_np: ^24.1.0
  android_id: ^0.4.0
  package_info_plus: ^8.1.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  screenshot: ^3.0.0
  connectivity_plus: ^6.1.0
  tray_manager: ^0.2.4
  window_manager: ^0.4.3
  flutter_local_notifications: ^18.0.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4
  sqflite_common_ffi_web: ^0.4.5+3
  path: ^1.8.3
  archive: ^3.6.1
  pool: ^1.5.1
  flutter_udid: ^3.0.0
  uuid: ^4.5.1
  grpc: ^4.0.1
  protobuf: ^3.1.0
  introduction_screen: ^3.1.14
  auto_route: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  analyzer: 6.4.0
  meta: ^1.11.0
  protoc_plugin: ^21.1.2
  auto_route_generator: ^9.0.0
  #analyzer_plugin: ^0.11.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
  generate: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: NotoSans
      # used as a fallback font
      # covers a lot of scripts and obscure unicode characters
      # https://fonts.google.com/specimen/Noto+Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: BrokenFilled
      fonts:
        - asset: assets/fonts/broken_filled.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf
          weight: 700
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf
          weight: 900


flutter_intl:
  enabled: true
  class_name: Localization
  use_deferred_loading: false

analyzer:
  plugins:
    - moor

flutter_icons:
  android: true
  ios: true
  image_path: "assets/bloomee_new_logo_gradient_bg.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "assets/bloomee_new_logo_gradient_bg.png"
  adaptive_icon_foreground: "assets/new_bloomee_logo_zoomedout.png"
  image_path: "assets/bloomee_new_logo_transparent_c.png"
  min_sdk_android: 28 # android min sdk min:16, default 21

  macos:
    generate: true
    image_path: "assets/bloomee_new_logo_c.png"
  windows:
    generate: true
    image_path: "assets/bloomee_new_logo_transparent_c.png"